### PR TITLE
Version 3

### LINKED ISSUE #260: Support for date-fns v3
Date-fns just released a stable version 3:
image

Is this package going to support the new version?

### LINKED ISSUE #266: Upgrade from date-fns 2.30 to 3.0.6: Cannot find module 'date-fns/format/index.js' from 'node_modules/date-fns-tz/format/index.js'
was on
date-fns:2.30.0
date-fns-tz:2.0.0

When upgraded to date-fns: 3.0.6 from 2.30.0 (date-fns-tz stays on v2.0.0 as this is their latest), i got this:

    Cannot find module 'date-fns/format/index.js' from 'node_modules/date-fns-tz/format/index.js'

    Require stack:
      node_modules/date-fns-tz/format/index.js
      node_modules/date-fns-tz/index.js
Any suggestions other than stay on the old version pls ?

### LINKED ISSUE #268: Unable to resolve path to module 'date-fns-tz'
- date-fns  version :   3.0.6,
- date-fns-tz version： 3.0.1,

I Install date-fns-tz-v3  to solve https://github.com/marnusw/date-fns-tz/issues/260#issuecomment-1867433216

but another error just show up 

截圖 2024-02-06 下午2 44 01

i just can't find my date-fns-tz module

even if  I change name to 'date-fns-tz-v3'

### PR DESCRIPTION
**Pull request by marnusw**
- [x] Rename `utcToZonedTime` to `toZonedTime` to make it less confusing (comments welcome!)
- [x] Rename `zonedTimeToUtc` to `fromZonedTime` to make it less confusing (comments welcome!)
- [x] Export all functions using named exports
- [x] Remove flow support

Closes #260
Closes #266
Closes #268

### CODE REVIEW

**Comment by nikensss** [comment]
Hi, @marnusw! If there's anything you would like some help with regarding the action list in the PR description let me know, maybe I can help.

**Comment by marnusw** [comment]
@nikensss thank you for the offer. I wanted to match what date-fns did for v3 as far as possible, but I realised the work I've done up to this point probably covers it, and the remainder can be done as interntal changes after the major version change.

I've published beta4 this morning without really testing it thoroughly. What would help, if you do have some time, is to test this beta please to see if it functions as expected. If so, I think it might be ready for the v3 release.

**Comment by dartess** [comment]
I tried `3.0.0-beta4`, and so far I can’t run my tests with vitest:
```
Error: Directory import '.../node_modules/date-fns-tz/esm/format' is not supported resolving ES modules imported from .../node_modules/date-fns-tz/esm/formatInTimeZone/index.js
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_UNSUPPORTED_DIR_IMPORT', url: 'file:///.../node_modules/date-fns-tz/esm/format' }

```
maybe it's not the lib's problem, but `3.0.0-beta.3` works fine

**Comment by gustavopch** [comment]
@fbellomi Possibly because of this?
> - [x] Rename utcToZonedTime to toZonedTime to make it less confusing (comments welcome!)

**Comment by fbellomi** [comment]
@gustavopch you're definitely right! --thanks

**Comment by samuelcole** [comment]
> I tried `3.0.0-beta4`, and so far I can’t run my tests with vitest:
> 
> ```
> Error: Directory import '.../node_modules/date-fns-tz/esm/format' is not supported resolving ES modules imported from .../node_modules/date-fns-tz/esm/formatInTimeZone/index.js
> ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
> Serialized Error: { code: 'ERR_UNSUPPORTED_DIR_IMPORT', url: 'file:///.../node_modules/date-fns-tz/esm/format' }
> ```
> 
> maybe it's not the lib's problem, but `3.0.0-beta.3` works fine

this is happening to me as well, i'm running nextjs if that helps

**Comment by marnusw** [comment]
ESM imports should be fixed in `3.0.0-beta.6`.

**Comment by dartess** [comment]
3.0.0-beta.6 works good

**Comment by mnigh** [comment]
@marnusw any idea why some of the checks are not running? maybe missing some credentials? i don't see either `Los_Angeles` or `Melbourne` (only `America/Los_Angeles` and `Australia/Melbourne`) in the [yml file](https://github.com/marnusw/date-fns-tz/blob/version3/.circleci/config.yml).

```bash
Writing SSH key for checkout to "/home/circleci/.ssh/id_rsa"
Writing SSH public key for checkout to "/home/circleci/.ssh/id_rsa.pub"
Cloning git repository
Cloning into '.'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error running git clone "git@github.com:marnusw/date-fns-tz.git": exit status 128
```

## Screenshot
Screen Shot 2024-04-05 at 09 02 25

**Comment by marnusw** [comment]
@mnigh I've been meaning to sort it out once v3 is live. I recently reauthorized CircleCI which then correctly started running the three checks that pass, but the other two are old ones which seem to still link to the old, now non-existent, CircleCI account and get triggered for new commits but then fail. I expect I will need to reach out to CircleCI support to get it resolved.

**Comment by samuelcole** [comment]
> 3.0.0-beta.6 works good

i've been clicking around my app, and beta 6 is working perfectly for us!

**Comment by jgravois** [comment]
3.0.0-beta.6 is working well in our app too. thanks for tackling this upgrade 🙏
